using System;
using UnityEngine;
using UnityEngine.InputSystem;

namespace Core.Input
{
    // Manually implementing the GameInput class structure usually generated by Unity's Input System
    public class GameInput
    {
        public GameplayActions Gameplay { get; }
        public UIActions UI { get; }

        public GameInput()
        {
            Gameplay = new GameplayActions(this);
            UI = new UIActions(this);
        }

        public struct GameplayActions
        {
            private GameInput m_Wrapper;
            public GameplayActions(GameInput wrapper) { m_Wrapper = wrapper; }

            public void Enable() { }
            public void Disable() { }
            public void SetCallbacks(IGameplayActions instance) 
            {
                // Manual binding using standard polling for now to avoid complex setup without asset
                // In a real project, this would use m_Wrapper.m_GameplayActionMap
            }
        }

        public struct UIActions
        {
            private GameInput m_Wrapper;
            public UIActions(GameInput wrapper) { m_Wrapper = wrapper; }

            public void Enable() { }
            public void Disable() { }
            public void SetCallbacks(IUIActions instance) { }
        }

        public interface IGameplayActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnDash(InputAction.CallbackContext context);
            void OnAttack(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
        }

        public interface IUIActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnResume(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnScrollWheel(InputAction.CallbackContext context);
            void OnMiddleClick(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
            void OnTrackedDevicePosition(InputAction.CallbackContext context);
            void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
        }
    }
}

